java -cp build/libs/hw4.jar edu.vt.ece.hw4.Benchmark normal BackoffLock 8 64000 Exponential
java -cp build/libs/hw4.jar edu.vt.ece.hw4.Benchmark normal BackoffLock 16 64000 Exponential
java -cp build/libs/hw4.jar edu.vt.ece.hw4.Benchmark normal BackoffLock 32 64000 Exponential
java -cp build/libs/hw4.jar edu.vt.ece.hw4.Benchmark normal BackoffLock 64 64000 Exponential
java -cp build/libs/hw4.jar edu.vt.ece.hw4.Benchmark normal BackoffLock 8 64000 Fibonacci
java -cp build/libs/hw4.jar edu.vt.ece.hw4.Benchmark normal BackoffLock 16 64000 Fibonacci
java -cp build/libs/hw4.jar edu.vt.ece.hw4.Benchmark normal BackoffLock 32 64000 Fibonacci
java -cp build/libs/hw4.jar edu.vt.ece.hw4.Benchmark normal BackoffLock 64 64000 Fibonacci
java -cp build/libs/hw4.jar edu.vt.ece.hw4.Benchmark normal BackoffLock 8 64000 Fixed
java -cp build/libs/hw4.jar edu.vt.ece.hw4.Benchmark normal BackoffLock 16 64000 Fixed
java -cp build/libs/hw4.jar edu.vt.ece.hw4.Benchmark normal BackoffLock 32 64000 Fixed
java -cp build/libs/hw4.jar edu.vt.ece.hw4.Benchmark normal BackoffLock 64 64000 Fixed
java -cp build/libs/hw4.jar edu.vt.ece.hw4.Benchmark normal BackoffLock 8 64000 Linear
java -cp build/libs/hw4.jar edu.vt.ece.hw4.Benchmark normal BackoffLock 16 64000 Linear
java -cp build/libs/hw4.jar edu.vt.ece.hw4.Benchmark normal BackoffLock 32 64000 Linear
java -cp build/libs/hw4.jar edu.vt.ece.hw4.Benchmark normal BackoffLock 64 64000 Linear
java -cp build/libs/hw4.jar edu.vt.ece.hw4.Benchmark normal BackoffLock 8 64000 Poly
java -cp build/libs/hw4.jar edu.vt.ece.hw4.Benchmark normal BackoffLock 16 64000 Poly
java -cp build/libs/hw4.jar edu.vt.ece.hw4.Benchmark normal BackoffLock 32 64000 Poly
java -cp build/libs/hw4.jar edu.vt.ece.hw4.Benchmark normal BackoffLock 64 64000 Poly